name: rinha-2026-3api

services:
  haproxy:
    image: haproxy:3.0-alpine
    volumes:
      - ./haproxy.3api.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "9999:9999"
    depends_on:
      api1:
        condition: service_healthy
      api2:
        condition: service_healthy
      api3:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "25MB"
    networks:
      - backend

  api1:
    image: fandangolas/rinha-2026-api:latest
    environment:
      SEARCHER: ivf
      IVF_PROBES: "5"
      GOGC: "off"
      GOMEMLIMIT: "75MiB"
      GOMAXPROCS: "1"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:9999/ready"]
      interval: 5s
      timeout: 2s
      retries: 10
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "100MB"
    networks:
      - backend

  api2:
    image: fandangolas/rinha-2026-api:latest
    environment:
      SEARCHER: ivf
      IVF_PROBES: "5"
      GOGC: "off"
      GOMEMLIMIT: "75MiB"
      GOMAXPROCS: "1"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:9999/ready"]
      interval: 5s
      timeout: 2s
      retries: 10
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "100MB"
    networks:
      - backend

  api3:
    image: fandangolas/rinha-2026-api:latest
    environment:
      SEARCHER: ivf
      IVF_PROBES: "5"
      GOGC: "off"
      GOMEMLIMIT: "75MiB"
      GOMAXPROCS: "1"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:9999/ready"]
      interval: 5s
      timeout: 2s
      retries: 10
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "100MB"
    networks:
      - backend

networks:
  backend:
    driver: bridge
