FROM rust:slim AS builder
WORKDIR /app
COPY rust-api/ .
RUN cargo build --release --locked

FROM debian:bookworm-slim
COPY --from=builder /app/target/release/rinha-api /usr/local/bin/rinha-api
EXPOSE 9999
CMD ["rinha-api"]
