FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y --no-install-recommends wget && rm -rf /var/lib/apt/lists/*
COPY rinha-api-bin /usr/local/bin/rinha-api
EXPOSE 9999
CMD ["rinha-api"]
